const Images = {
  intro1: require('../assets/images/intro1.png'),
  intro2: require('../assets/images/intro2.png'),
  intro3: require('../assets/images/onePlantLarge.png'),
  fb: require('../assets/images/fb.png'),
  gmail: require('../assets/images/gmail.png'),
  close: require('../assets/images/close.png'),
  memberShipPlant: require('../assets/images/memberShipPlant.png'),
  rightSign: require('../assets/images/rightSign.png'),
  bestDeal: require('../assets/images/bestDeal.png'),
  homeActive: require('../assets/images/homActive.png'),
  homeInActive: require('../assets/images/homeInActive.png'),
  mediActive: require('../assets/images/mediActive.png'),
  mediInActive: require('../assets/images/mediInActive.png'),
  accountActive: require('../assets/images/accountActive.png'),
  accountInActive: require('../assets/images/accountInActive.png'),
  homeCloud: require('../assets/images/homeCloud.png'),
  homeInviteTree: require('../assets/images/homeInviteTree.png'),
  homegirl: require('../assets/images/homegirl.png'),
  homeGreenPlay: require('../assets/images/homeGreenPlay.png'),
  homeModalCloud: require('../assets/images/homeModalCloud.png'),
  homeModaltree: require('../assets/images/homeModaltree.png'),
  homeWhitePlay: require('../assets/images/homeWhitePlay.png'),
  mediStreesFree: require('../assets/images/mediStreesFree.png'),
  UnlockCloud: require('../assets/images/UnlockCloud.png'),
  accountTree: require('../assets/images/accountTree.png'),
  accountoval: require('../assets/images/accountoval.png'),
  accountOvaltree: require('../assets/images/accountOvaltree.png'),
  forest: require('../assets/images/forest.png'),
}
export default Images